import { useState }         from "react";
import { useInvoiceStore }  from "../store/invoiceStore";
import { exportCSV, exportJSON, exportMarkdown } from "../utils/exportHelpers";
import { downloadServerPDF } from "../services/invoiceApiService";
import { formatCurrency }    from "../utils/formatters";
import { filterByStatus, sumAmounts } from "../utils/invoiceHelpers";
import { INVOICE_STATUSES } from "../constants";

export function ExportPage() {
  const { state:{ invoices } } = useInvoiceStore();
  const [done, setDone]   = useState(null);
  const [err,  setErr]    = useState(null);
  const apiBase = localStorage.getItem("apiBaseUrl");
  const total   = sumAmounts(invoices);

  const opts = [
    { id:"csv",  label:"CSV Spreadsheet", desc:"Open in Excel or Google Sheets. All fields, one row per invoice.", icon:"⬡", accent:"#2d7a4f", fn:()=>{exportCSV(invoices);setDone("csv");} },
    { id:"json", label:"JSON Export",     desc:"Full dump including AI summaries — ideal for re-importing.",       icon:"{}",accent:"#1a5c9e", fn:()=>{exportJSON(invoices);setDone("json");} },
    { id:"md",   label:"Markdown Report", desc:"Human-readable table. Paste into Notion or Confluence.",          icon:"#", accent:"#b85c00", fn:()=>{exportMarkdown(invoices);setDone("md");} },
    { id:"pdf",  label:"PDF (Server)",    desc:"Formatted PDF generated by iText on Spring Boot backend.",        icon:"⬡", accent:"#c84b2f",
      fn:async()=>{ try{await downloadServerPDF();setDone("pdf");}catch(e){setErr(e.message);} },
      disabled:!apiBase },
  ];

  return (
    <div style={{ padding:"32px 36px", flex:1, maxWidth:900 }}>
      <div className="fu" style={{ marginBottom:28 }}>
        <div style={{ fontSize:10, fontFamily:"var(--mono)", color:"var(--ink3)", letterSpacing:2 }}>DOWNLOAD</div>
        <h1 style={{ fontSize:30, fontWeight:800, letterSpacing:-1.2, marginTop:3 }}>Export Data</h1>
      </div>

      <div style={{ display:"grid", gridTemplateColumns:"repeat(2,1fr)", gap:14, marginBottom:28 }}>
        {opts.map((o,i)=>(
          <button key={o.id} className="fu" onClick={!o.disabled?o.fn:undefined} style={{ background:"#fff", border:"1px solid var(--border)", borderTop:`3px solid ${o.accent}`, borderRadius:12, padding:"24px 20px", textAlign:"left", cursor:o.disabled?"not-allowed":"pointer", transition:"all .15s", animationDelay:`${i*60}ms`, opacity:o.disabled?.5:1, boxShadow:done===o.id?"var(--shadow-lg)":"none" }}
            onMouseEnter={e=>{if(!o.disabled)e.currentTarget.style.boxShadow="var(--shadow-lg)";}}
            onMouseLeave={e=>{if(done!==o.id)e.currentTarget.style.boxShadow="none";}}>
            <div style={{ fontSize:24, marginBottom:10 }}>{o.icon}</div>
            <div style={{ fontWeight:700, fontSize:14, marginBottom:6 }}>{o.label}</div>
            <div style={{ fontSize:12, color:"var(--ink3)", lineHeight:1.5, marginBottom:12 }}>{o.desc}</div>
            <div style={{ fontFamily:"var(--mono)", fontSize:11, color:o.accent, fontWeight:700 }}>
              {done===o.id?"✓ Downloaded":o.disabled?"Requires API URL":"Download ↓"}
            </div>
          </button>
        ))}
      </div>

      {err && <div style={{ color:"var(--accent)", fontSize:12, fontFamily:"var(--mono)", marginBottom:16 }}>✕ {err}</div>}

      <div className="fu" style={{ background:"#fff", border:"1px solid var(--border)", borderRadius:10, overflow:"hidden", animationDelay:"260ms" }}>
        <div style={{ padding:"13px 18px", borderBottom:"1px solid var(--border)", fontSize:10, fontFamily:"var(--mono)", color:"var(--ink3)", letterSpacing:1.5 }}>
          PREVIEW — {invoices.length} records · {formatCurrency(total)} total
        </div>
        <table style={{ width:"100%", borderCollapse:"collapse" }}>
          <thead><tr style={{ background:"var(--paper)", borderBottom:"1px solid var(--border)" }}>
            {["Status","Count","Total Amount","% of Total"].map(h=><th key={h} style={{ padding:"9px 18px", textAlign:"left", fontSize:9.5, fontFamily:"var(--mono)", color:"var(--ink3)", letterSpacing:1, fontWeight:500 }}>{h}</th>)}
          </tr></thead>
          <tbody>
            {INVOICE_STATUSES.map(s=>{
              const grp=filterByStatus(invoices,s);
              const amt=sumAmounts(grp);
              const pct=total>0?(amt/total*100).toFixed(1):"0.0";
              return (
                <tr key={s} style={{ borderBottom:"1px solid var(--border)" }}>
                  <td style={{ padding:"11px 18px" }}><span style={{ fontFamily:"var(--mono)", fontSize:11.5, fontWeight:700, color:{PAID:"var(--success)",OVERDUE:"var(--accent)",PENDING:"var(--warn)",PROCESSING:"var(--info)"}[s] }}>{s}</span></td>
                  <td style={{ padding:"11px 18px", fontFamily:"var(--mono)", fontSize:13 }}>{grp.length}</td>
                  <td style={{ padding:"11px 18px", fontFamily:"var(--mono)", fontSize:13 }}>{formatCurrency(amt)}</td>
                  <td style={{ padding:"11px 18px" }}>
                    <div style={{ display:"flex", alignItems:"center", gap:8 }}>
                      <div style={{ flex:1, height:4, background:"var(--paper2)", borderRadius:2, overflow:"hidden" }}><div style={{ height:"100%", width:`${pct}%`, background:"var(--ink)", borderRadius:2 }}/></div>
                      <span style={{ fontFamily:"var(--mono)", fontSize:11, color:"var(--ink3)", width:36 }}>{pct}%</span>
                    </div>
                  </td>
                </tr>
              );
            })}
            <tr style={{ background:"var(--paper)", borderTop:"2px solid var(--border)" }}>
              <td style={{ padding:"11px 18px", fontWeight:800, fontSize:13 }}>Total</td>
              <td style={{ padding:"11px 18px", fontFamily:"var(--mono)", fontSize:13, fontWeight:700 }}>{invoices.length}</td>
              <td style={{ padding:"11px 18px", fontFamily:"var(--mono)", fontSize:13, fontWeight:700 }}>{formatCurrency(total)}</td>
              <td style={{ padding:"11px 18px", fontFamily:"var(--mono)", fontSize:11, color:"var(--ink3)" }}>100%</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}
